### ISSUE TITLE
[prtvol2csv] Support PRT file generated by OPM Flow?

### ISSUE THREAD

**Issue by rnyb** [equinor/subscript#387]
Alternatively, it may be that the "fix" should be with OPM Flow?

stderr output from test:

Traceback (most recent call last):

  File "/prog/res/komodo/2021.05.01-py36-rhel7/root/bin/prtvol2csv", line 8, in <module>
    sys.exit(main())
  File "/prog/res/komodo/2021.05.01-py36-rhel7/root/lib/python3.6/site-packages/subscript/prtvol2csv/prtvol2csv.py", line 309, in main
    simvolumes_df = currently_in_place_from_prt(prt_file, "FIPNUM")
  File "/prog/res/komodo/2021.05.01-py36-rhel7/root/lib/python3.6/site-packages/subscript/prtvol2csv/prtvol2csv.py", line 194, in currently_in_place_from_prt
    date_str = available_dates[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by berland** [comment]
The "PRT" file emitted by flow does not look like the corresponding for E100, or for E300 for which prtvol2csv does not work either (see #222). 

Scraping the PRT file for this data is not a very robust strategy, we should rather exchange it with a more robust procedure that works for E100, E300 and OPM, finding data in well defined binary files.

**Comment by berland** [comment]
> The "PRT" file emitted by flow does not look like the corresponding for E100

This statement was false.  Fixed in https://github.com/equinor/ecl2df/pull/315
