### ISSUE TITLE
interp_relperm fails with "Incoming pc not decreasing" when running with family-2 tables.

### ISSUE THREAD

**Issue by WestfalNamur** [equinor/subscript#406]
Context: Interpolating relative permeability includes form SGFN, SOF3, and SWFN tables.
Python: /prog/res/komodo/2021.07.00-py36-rhel7/root/bin/python

Reproduce:
```
interp_relperm -c interp_relperm_config.yml
```

Error:
```
Traceback (most recent call last):
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/bin/interp_relperm", line 8, in <module>
    sys.exit(main())
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/lib/python3.6/site-packages/subscript/interp_relperm/interp_relperm.py", line 414, in main
    process_config(cfg, Path(args.root_path))
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/lib/python3.6/site-packages/subscript/interp_relperm/interp_relperm.py", line 534, in process_config
    relperm_delta_s,
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/lib/python3.6/site-packages/subscript/interp_relperm/interp_relperm.py", line 355, in make_interpolant
    base = make_wateroilgas(base_df.loc[satnum], delta_s)
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/lib/python3.6/site-packages/subscript/interp_relperm/interp_relperm.py", line 316, in make_wateroilgas
    pccolname="PCOW",
  File "/prog/res/komodo/2021.07.00-py36-rhel7/root/lib/python3.6/site-packages/pyscal/wateroil.py", line 369, in add_fromtable
    raise ValueError("Incoming pc not decreasing")
ValueError: Incoming pc not decreasing

```

Config:
```
base:
  - sgfn_base.inc
  - sof3_base.inc
  - swfn_base.inc

high:
  - sgfn_optimistic.inc
  - sof3_optimistic.inc
  - swfn_optimistic.inc

low:
  - sgfn_pessimistic.inc
  - sof3_pessimistic.inc
  - swfn_pessimistic.inc

result_file: outfile.inc

family: 2 # Eclipse keyword family. Optional. 1 is default, 2 is the alternative

#delta_s: 0.02  # Optional: resolution of Sw/Sg, defaulted to 0.01

interpolations:
  - tables: []
    param_w:  0
    param_g:  0 
```

Inputs to reproduce:
[isolated.zip](https://github.com/equinor/subscript/files/6867477/isolated.zip)

Data source:
SCAL group input from 2017

It seems the script adds a column POWC for wo_dframe['PCOW'] with values [1,0,0,...,0] in function make_wateroilgas before passing it to PyScal via wog.wateroil.add_fromtable().
By changing the function to filling the column with decreasing tables from 1 to 0 the function passes, however I do not know if this is valid.

**Comment by berland** [comment]
Can you pinpoint where in the source you find this [1,0,....,0] ? 

What does the input capillary pressure look like? Zero, or decreasing?

**Comment by WestfalNamur** [comment]
The input capillary pressure is 0.

**Comment by berland** [comment]
I have tried reproducing this with capillary pressure set to zero, but failed to see the problem, so more information is needed.

**Comment by WestfalNamur** [comment]
I can share the input via Slack if you like.

**Comment by berland** [comment]
This error is due to defaults in use by the SWFN input tables:
```
SWFN
0.05 0.000   1
0.00  0.0004  1*
0.08 0.001  1*
[snip]
0.99 0.9 1*
1.00  1.0  0
/
```

`interp_relperm` parses this through `ecl2df`, which again parses this using OPM. The Eclipse manual states that the defaulted capillary pressures should be linearly interpolated, but they are returned to ecl2df as zeros. This correctly crashes in `pyscal` with a `ValueError`.

**Comment by berland** [comment]
https://github.com/OPM/opm-common/issues/2598

**Comment by berland** [comment]
This issue is solved when https://github.com/equinor/ecl2df/issues/339 is merged.
